#!/usr/bin/env python3
from pathlib import Path
from github_api import get_stats
ROOT=Path(__file__).resolve().parents[1]
try: s=get_stats()
except Exception:
    s=None
for theme in ['dark','light']:
    light=theme=='light'; bg='#ffffff' if light else '#0d1117'; border='#d0d7de' if light else '#30363d'; text='#1f2328' if light else '#c9d1d9'; muted='#656d76' if light else '#8b949e'; green='#1a7f37' if light else '#39d353'
    if s:
        rows=[('Repos',s['repositories']),('Followers',s['followers']),('Following',s['following']),('Stars',s['stars']),('Forks',s['forks'])]
        content=''.join(f'<text x="{x}" y="{y}" fill="{muted}" font-family="monospace" font-size="12">{k}</text><text x="{x+110}" y="{y}" fill="{text}" font-family="monospace" font-size="14" font-weight="700">{v}</text>' for (k,v),(x,y) in zip(rows,[(32,62),(205,62),(32,110),(205,110),(32,158)]))
        title='GitHub activity — live repository data'
    else:
        title='GitHub activity — run radar.yml to refresh'; content=f'<text x="32" y="92" fill="{muted}" font-family="monospace" font-size="13">Live data is generated by GitHub Actions.</text>'
    svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 520 205"><rect x="4" y="4" width="512" height="197" rx="18" fill="{bg}" stroke="{border}"/><text x="32" y="34" fill="{green}" font-family="monospace" font-size="14" font-weight="700">{title}</text>{content}</svg>'
    (ROOT/'assets'/f'stats-{theme}.svg').write_text(svg,encoding='utf-8')
